version: "3"
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
        volumes: 
            - ./:/app
        working_dir: /app
        command: bash -c "dotnet restore
                        && dotnet build
                        && chmod +x ./entrypoint.sh
                        && /bin/bash ./entrypoint.sh"
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "123@Qasd"
            ACCEPT_EULA: "Y"
